captcha-service/binding.gyp, captcha-service/package-lock.json, captcha-service/package.json, captcha-service/src/index.ts
Reverts bcgov/MOH-MSP-Enrolment#7
=> Revert "Update captcha service"

msp/package-lock.json, msp/package.json, msp/src/app/app.component.spec.ts, msp/src/app/app.component.ts, msp/src/app/app.module.ts, msp/src/app/modules/account/components/moving-information/moving-information.component.html, msp/src/app/modules/account/components/moving-information/moving-information.component.spec.ts, msp/src/app/modules/account/components/moving-information/moving-information.component.ts, msp/src/app/modules/account/pages/child-info/remove-child/remove-child.component.html, msp/src/app/modules/account/pages/child-info/remove-child/remove-child.component.spec.ts, msp/src/app/modules/account/pages/child-info/remove-child/remove-child.component.ts, msp/src/app/modules/account/pages/contact-info/contact-info.component.html, msp/src/app/modules/account/pages/contact-info/contact-info.component.spec.ts, msp/src/app/modules/account/pages/contact-info/contact-info.component.ts, msp/src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.html, msp/src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.spec.ts, msp/src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.ts, msp/src/app/modules/assistance/pages/contact/assist-contact.component.html, msp/src/app/modules/assistance/pages/contact/assist-contact.component.ts, msp/src/app/modules/benefit/pages/contact-info/address.component.html, msp/src/app/modules/benefit/pages/contact-info/address.component.spec.ts, msp/src/app/modules/benefit/pages/contact-info/address.component.ts, msp/src/app/modules/enrolment/pages/address/address.component.html, msp/src/app/modules/enrolment/pages/address/address.component.spec.ts, msp/src/app/modules/enrolment/pages/address/address.component.ts, msp/src/app/modules/enrolment/pages/child-info/child-info.component.html, msp/src/app/modules/enrolment/pages/child-info/child-info.component.spec.ts, msp/src/app/modules/enrolment/pages/child-info/child-info.component.ts, msp/src/app/services/spa-env.service.ts, msp/src/proxy.conf.json
=> Add address service into all MSP forms.

msp/package-lock.json, msp/package.json, msp/src/app/modules/account/components/moving-information/moving-information.component.html, msp/src/app/modules/account/pages/child-info/remove-child/remove-child.component.html, msp/src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.html, msp/src/app/modules/assistance/pages/contact/assist-contact.component.html, msp/src/app/modules/benefit/pages/contact-info/address.component.html, msp/src/app/modules/enrolment/pages/address/address.component.html, msp/src/app/modules/enrolment/pages/child-info/child-info.component.html, msp/src/app/modules/msp-core/components/address-review-part/address-review-part.component.html
=> Update to new version of common lib and address fixes.

msp/package-lock.json, msp/package.json
=> Update version to MSP v3.3.3.

msp/package-lock.json, msp/package.json
=> Update common lib version.

msp/src/app/modules/account/components/moving-information/moving-information.component.html, msp/src/app/modules/account/pages/child-info/remove-child/remove-child.component.html, msp/src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.html, msp/src/app/modules/assistance/pages/contact/assist-contact.component.html, msp/src/app/modules/enrolment/pages/child-info/child-info.component.html
=> Added address tip box when address validator is enabled.

msp/package-lock.json, msp/package.json
=> Common lib bump.

msp/src/app/modules/enrolment/pages/confirmation/confirmation.component.html, msp/src/environments/environment.prod.ts, msp/src/environments/environment.ts
=> MSP Enrolment confirmation page text changes.

msp/package.json, msp/src/app/modules/account/pages/confirmation/confirmation.component.html
=> Update DEAM ICBC copy

msp/package-lock.json, msp/package.json, msp/src/app/modules/enrolment/pages/confirmation/confirmation.component.html
Kai said he missed this when checking the wireframes.
=> Text changes

msp/package-lock.json, msp/package.json, msp/src/index.html
=> Update library version and add zoom on mobile

msp/package.json, msp/src/app/modules/account/components/moving-information/moving-information.component.html, msp/src/app/modules/enrolment/pages/personal-info/personal-info.component.html, msp/src/app/modules/enrolment/pages/personal-info/personal-info.component.ts
=> DEAM-546 and fix for disabled continue

msp/src/app/modules/account/pages/child-info/child-info.component.ts
=> Fix bug where temp perm couldnt be leaving BC after studies

msp/src/app/modules/account/services/msp-api-account.service.ts
=> Fill empty mailing address with residential address

msp/package-lock.json, msp/package.json, msp/src/app/modules/account/components/moving-information/moving-information.component.html, msp/src/app/modules/account/components/personal-information/personal-information.component.html, msp/src/app/modules/account/components/update-request/update-request.component.html, msp/src/app/modules/account/pages/authorize/authorize.component.html, msp/src/app/modules/account/pages/child-info/add-child/add-child.component.html, msp/src/app/modules/account/pages/child-info/remove-child/remove-child.component.html, msp/src/app/modules/account/pages/home/home.component.html, msp/src/app/modules/account/pages/personal-info/personal-info.component.html, msp/src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html, msp/src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.html, msp/src/app/modules/account/services/msp-api-account.service.ts, msp/src/app/modules/enrolment/services/msp-api-enrolment.service.ts
=> Fix bugs and update version

msp/package-lock.json, msp/package.json, msp/src/app/app.component.spec.ts
Also fixed a test that happened to be broken. Ran `npm i karma@latest --save-dev`
=> Fix broken test and update karma

msp/package-lock.json, msp/package.json, msp/src/app/modules/account/services/msp-api-account.service.ts
=> Remove redundant broken code

jha/package-lock.json, jha/package.json, jha/src/components/TipBox.vue, jha/src/components/enrolment/FPCWidget.vue, jha/src/settings.js, jha/src/views/enrolment/FPCareInfoPage.vue
=> FPC page progress.

jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/FPCareInfoPage.vue
=> Updating store with FPC data.

jha/src/components/ReviewTable.vue, jha/src/components/enrolment/ReviewTableList.vue, jha/src/views/enrolment/ContactInfoPage.vue, jha/src/views/enrolment/ReviewPage.vue
Bug fix, content and feature addition
=> Implement most review page functionality, fix nav bug

jha/package-lock.json, jha/package.json
=> JHA: common library version bump (v1.0.63).

jha/src/helpers/validators.js, jha/src/views/enrolment/PersonalInfoPage.vue
=> Updates to Personal Info page.

msp/package-lock.json, msp/package.json
=> MSP Taiwan update.

jha/src/views/enrolment/ContactInfoPage.vue
Added tip box for phone number
Hide residential address when only FPC form is selected
=> feat: JHA ContactInfo updates

jha/package-lock.json, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
Feature addition, content addition
=> Add button functionality to removiing/adding spouse, tipboxes

jha/src/App.vue, jha/src/router/index.js, jha/src/router/routes.js, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
=> JHA: placeholder questionnaire pages.

jha/src/views/enrolment/ContactInfoPage.vue
Changed country and region(if in canada) to CountrySelect and RegionSelect components.
=> feat: JHA-ContactInfo country/region select

jha/src/constants/radio-options.js, jha/src/helpers/validators.js, jha/src/views/enrolment/PersonalInfoPage.vue
=> Personal Info page fixes.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.17).

jha/src/constants/select-options.js, jha/src/views/enrolment/PersonalInfoPage.vue
=> JHA: Personal info page citizenship document options.

jha/package-lock.json, jha/package.json, jha/src/router/routes.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/PersonalInfoPage.vue
=> Account holder page bug fixes.

jha/package-lock.json, jha/package.json, jha/src/views/enrolment/PersonalInfoPage.vue
=> Personal info fixes

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.18).

jha/src/components/ConsentModal.vue, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue
=> JHA: Made info collection notice content dynamic based on form selection

jha/src/views/enrolment/ContactInfoPage.vue
Fixed bugs:
JHA-257 Contact Information required messages
JHA-258 Contact Information Label names
JHA-259 Contact information page layout
Version bump for common-lib-vue to add inputStyle to restrict width of CountrySelect and RegionSelect components.
=> Contact info fixes

jha/src/components/ConsentModal.vue, jha/src/helpers/validators.js, jha/src/router/routes.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/PersonalInfoPage.vue
=> JHA: Personal Info page validations and styles.

jha/src/views/enrolment/SpouseInfoPage.vue
=> Spouse bug fixes

jha/package-lock.json, jha/package.json
=> JHA: Version bump (v0.1.19).

jha/package-lock.json, jha/package.json, jha/src/helpers/validators.js, jha/src/views/enrolment/PersonalInfoPage.vue
There shouldn't need to be any changes required to existing `DateInput` component usages, unless the date needs to be reset while the component is still rendered. In which case, copy the included example in this PR.
=> JHA: Update common library version (fix for invalid date clearing bug).

jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
Add eligibility questionnaires for MSP, FPC, and SB.
=> Jha eligibility

jha/src/views/enrolment/PersonalInfoPage.vue
=> JHA: Account holder page bug fixes.

jha/package-lock.json, jha/src/helpers/validators.js, jha/src/settings.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/SpouseInfoPage.vue
=> Spouse info fixes

jha/package-lock.json, jha/package.json, jha/src/store/states/enrolment-module-dummy-data.js, jha/src/views/enrolment/ContactInfoPage.vue
Fixes for JHA-260
Updated dummy Data for smoother dev navigation.
=> Contact info fixes2

jha/src/views/enrolment/SpouseInfoPage.vue
=> Fix validation initialize

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.20).

jha/package-lock.json, jha/package.json, jha/src/store/states/enrolment-module-dummy-data.js, jha/src/views/enrolment/PersonalInfoPage.vue
=> Added `SINInput` component usage to Account Holder page.

msp/package-lock.json, msp/package.json, msp/src/app/modules/msp-core/components/support-documents/support-documents.component.ts
=> Update gender designation documents and version

msp/package-lock.json, msp/package.json, msp/src/app/modules/msp-core/models/support-documents.enum.ts
=> Add front and back text

jha/src/views/enrolment/SpouseInfoPage.vue
=> Fix for error messages and show logic

jha/src/store/states/enrolment-module-dummy-data.js, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> Update child info page, fix suppben change

msp/package-lock.json, msp/package.json
=> CO 11228: Revert Taiwan change.

jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/FormSelectionPage.vue
Add disabled checkboxes based on form eligibility
=> Add gtrs for form select and disable checkboxes

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.23).

jha/package-lock.json, jha/package.json, jha/src/App.vue, jha/src/views/enrolment/PersonalInfoPage.vue
=> JHA: personal info page changes.

jha/package-lock.json
=> Run npm audit fix for JHA

jha/package-lock.json, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> Fix spouse bugs, update spouse and child fu and si's

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.24).

jha/package-lock.json, jha/package.json
=> Bump common lib

jha/src/store/states/enrolment-module-dummy-data.js, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> Add stepper mixins and fix dummy data for suppbens

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.25).

jha/src/components/enrolment/Child.vue, jha/src/helpers/validators.js, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> Remove a lot of bugs, add validations

jha/package-lock.json, jha/package.json
=> JHA: update common lib version.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.26).

jha/openshift/templates/config.yaml, jha/src/App.vue, jha/src/components/ConsentModal.vue, jha/src/components/SampleImageTipBox.vue, jha/src/services/api-service.js, jha/src/services/log-service.js, jha/src/services/spa-env-service.js, jha/src/views/enrolment/FPCareInfoPage.vue, jha/vue.config.js
This change is to update the URL from "/jha" to "/ahdc".
Once this is merged to "main", the OpenShift nginx config will need to be reprocessed to reflect the new mod-rewrite rule.
=> JHA: update "jha" to be new acronym "ahdc".

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.27).

jha/package-lock.json, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/ChildInfoPage.vue
=> Fix child data saving bug

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue, jha/src/services/api-service.js, jha/src/settings.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/ReviewPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, msp-service/src/index.js
Not fully function yet, but I'd like to merge in what I have so far.
=> JHA: MSP submission payload.

jha/src/components/enrolment/Child.vue
=> Fix bugs related to child school info

msp-service/src/index.js
=> Fixed msp-service and added "/health" endpoint.

msp-service/src/index.js
=> Add "submit-attachment" handling to account for JHA program UUIDs.

jha/src/components/enrolment/Child.vue, jha/src/constants/radio-options.js, jha/src/router/routes.js, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
Bug fixes, one content update to child
=> Fix bugs in child, spouse, supben

msp/package-lock.json, msp/package.json, msp/src/app/modules/msp-core/components/support-documents/support-documents.component.ts, msp/src/app/modules/msp-core/models/support-documents.enum.ts
=> Remove passport as option for certain fields

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.28).

jha/package-lock.json, jha/package.json, jha/src/services/api-service.js, jha/src/views/enrolment/ReviewPage.vue, msp-service/src/index.js
=> JHA: attachment API call fix, and updates to JHA API routing in "msp-service".

jha/src/mixins/page-stepper-mixin.js, jha/src/router/index.js, jha/src/router/routes.js, jha/src/services/api-service.js, jha/src/views/enrolment/ConsentPage.vue, jha/src/views/enrolment/ReviewPage.vue, jha/src/views/enrolment/SubmissionPage.vue
=> JHA: Declaration and Consent page.

jha/src/components/SuppBenWidget.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> Fix suppbens bug related to neg nums

jha/src/constants/eqMsgCodes.js, jha/src/constants/radio-options.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
=> Fix eligibility questionnaire bugs

jha/src/views/enrolment/DocumentsPage.vue
- [] Unit tests for these changes were added (if applicable)
Adds validations to Documents page so all required documents must be uploaded before it'll allow a user to proceed. The page also produces a descriptive error when this happens.
No automated tests added yet, although hopefully they can be added with the rest down the road. I did manually test the changes, though.
=> Add validations to documents page

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.29).

msp/package-lock.json, msp/package.json, msp/src/app/modules/account/components/moving-information/moving-information.component.html, msp/src/app/modules/account/components/person-card/person-card.component.ts, msp/src/app/modules/assistance/pages/review/review.component.html, msp/src/app/modules/enrolment/components/person-review-card/person-review-card.component.ts, msp/src/app/modules/msp-core/components/address-card-part/address-card-part.component.html, msp/src/app/modules/msp-core/components/address-review-part/address-review-part.component.html, msp/src/app/modules/msp-core/components/moving-information/moving-information.component.html, msp/src/app/modules/msp-core/components/moving-information/moving-information.component.ts, msp/src/app/modules/msp-core/components/person-card/person-card.component.ts, msp/src/app/modules/msp-core/models/canadian-status.enum.ts
Content update
Effectively changes enrolment, deam, assistance, and sup bens country labels to "Jurisdiction"
=> Country label change (moh-common-lib update)

jha/src/components/enrolment/Child.vue
=> Clear province if country is changed

jha/src/views/enrolment/MSPEligibilityPage.vue
=> Fix content

jha/src/constants/immigration-status-types.js, jha/src/services/api-service.js
=> JHA: Submit to API endpoint.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.30).

jha/src/components/SampleImageTipBox.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
Feature addition
Left modal-footer class for readability
=> Add modal close button, fix typo

jha/src/App.vue, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
=> Various bug fixes and content updates

jha/src/mixins/page-stepper-mixin.js, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
=> Fix suppben routing and missing link

jha/src/services/api-service.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/ConsentPage.vue
=> JHA: FPC submission payload.

jha/src/views/enrolment/PersonalInfoPage.vue
=> Add PHN and validation to personal info page

jha/src/store/states/enrolment-module-dummy-data.js, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
Feature additions and bug fixes
=> Add spouse PHN and SIN, update gender conditional

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> Update selects to disable placeholder

jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/ChildInfoPage.vue
Bug fix and feature addition
Fixed some of the tabbing in the template which might make this PR a little hard to read through.
=> Conditionally show child inputs based on form selected, add PHN

jha/src/services/api-service.js, jha/src/views/enrolment/ConsentPage.vue
=> JHA: SB submission payload.

jha/src/components/enrolment/Child.vue
=> Fix child bug

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.31).

jha/src/components/enrolment/Child.vue, jha/src/components/enrolment/ReviewTableList.vue, jha/src/constants/immigration-status-types.js, jha/src/views/enrolment/ContactInfoPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> Change country to jurisdiction

jha/src/views/enrolment/DocumentsPage.vue
=> JHA: Documents page tax year, and FileUploader implementation fixes.

jha/src/components/ConsentModal.vue, jha/src/components/enrolment/FPCWidget.vue, jha/src/services/api-service.js, jha/src/store/modules/app-module.js, jha/src/views/enrolment/FPCareInfoPage.vue
=> JHA: FPC widget.

jha/src/services/api-service.js
=> JHA: SB submission payload updates.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.32).

jha/src/App.vue, jha/src/router/routes.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/ConsentPage.vue, jha/src/views/enrolment/ContactInfoPage.vue, jha/src/views/enrolment/DocumentsPage.vue, jha/src/views/enrolment/FPCareInfoPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/ReviewPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SubmissionErrorPage.vue, jha/src/views/enrolment/SubmissionPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> JHA: Route guards.

jha/package-lock.json, jha/package.json
=> JHA: common lib bump (v1.0.85).

jha/src/components/enrolment/Child.vue
=> JHA: fixed child validation.

jha/src/store/modules/enrolment-module.js, jha/src/store/states/enrolment-module-dummy-data.js, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
=> JHA: EQ fixes.

jha/src/components/SuppBenWidget.vue
=> JHA: SB widget styles and logic.

jha/src/views/enrolment/PersonalInfoPage.vue
=> JHA: non-Canada validator.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.33).

jha/src/components/enrolment/FPCWidget.vue
=> JHA: fixed FPC widget error.

jha/src/store/states/enrolment-module-dummy-data.js, jha/src/views/enrolment/ConsentPage.vue
=> JHA: fix dummy data.

jha/src/components/ErrorBox.vue, jha/src/components/SuccessBox.vue, jha/src/services/api-service.js, jha/src/store/modules/enrolment-module.js, jha/src/views/enrolment/ConsentPage.vue, jha/src/views/enrolment/SubmissionPage.vue
=> JHA: submission page.

jha/package-lock.json, jha/package.json
=> JHA: common lib version bump.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.34).

jha/src/views/enrolment/FPCareInfoPage.vue
=> JHA: FPC check eligibility endpoint error handling.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.35).

jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> Fix bugs related to dates, wording, and country select

jha/src/components/enrolment/ReviewTableList.vue
--Hide spouse section entirely if there's no spouse
--Add missing field data
--Move a bunch of stuff into conditionals, eg. only display X field if user is applying for MSP, etc.
--Minor formatting changes
=> Review Page standalone fields

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.36).

jha/openshift/templates/build.yaml
=> JHA: Increase OpenShift memory limit.

jha/src/components/enrolment/FPCWidget.vue, jha/src/views/enrolment/FPCareInfoPage.vue
=> JHA: FPC coverage level now factoring in spouse with correct date check.

jha/src/views/enrolment/SpouseInfoPage.vue
=> JHA: empty spouse income and RDSP when no spouse to be included.

jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/ContactInfoPage.vue
=> JHA: truncate Address Doctor city to 25 chars.

jha/src/App.vue
=> JHA: fix maintenance flag.

jha/src/views/enrolment/SpouseInfoPage.vue
=> JHA: add missing `id` props on spouse page.

jha/src/views/enrolment/ConsentPage.vue, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
=> JHA: Splunk logging fixes.

jha/src/views/enrolment/DocumentsPage.vue
=> JHA-28: fix documents page tip box content.

jha/src/components/enrolment/ReviewTableList.vue, jha/src/constants/radio-options.js
--Changes radio options
--Updates review page to display properly
--Adds getFormattedGender() function to make gender display code more reusable
=> Gender X stuff

jha/package-lock.json, jha/package.json, jha/src/views/enrolment/SubmissionPage.vue
=> JHA: Submission page updates.

jha/src/views/enrolment/SpouseInfoPage.vue
=> JHA: reset spouse CRA docs when no spouse chosen.

jha/src/components/ReviewTable.vue, jha/src/components/enrolment/ReviewTableList.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
--adds underlining to review page
--fixes line height per Ernesto's recommendation
--adds word break to prevent text from overflowing
--fixes review page order to be consistent between sections
--minor punctuation/capitalization/wording fixes for consistency
--change "lived in BC since birth" to only display if user is a citizen living in BC without MSP
--change documents counter to only display if user is applying for MSP
--change supplementary benefits document counter to include documents in the stepper page
--add max length to supplementary benefits income fields
--checks residency status against constants instead of plain text
=> Review page fixes

jha/package-lock.json, jha/package.json, jha/src/components/ReviewTable.vue, jha/src/components/enrolment/FPCWidget.vue, jha/src/components/enrolment/ReviewTableList.vue, jha/src/helpers/fpc-helpers.js, jha/src/services/api-service.js
=> JHA: FPC distribution bar refactor.

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.37).

jha/src/services/api-service.js
=> Fix payload issues

jha/src/components/enrolment/ReviewTableList.vue
=> Remove double gender code

jha/src/services/api-service.js
=> Adjusted country field lengths

jha/src/components/enrolment/ReviewTableList.vue, jha/src/views/enrolment/DocumentsPage.vue
=> Edit review data and add tipbox to doc page

.github/workflows/jha-web.yaml, jha/.eslintrc.js, jha/openshift/templates/build.yaml, jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue, jha/src/components/enrolment/ReviewTableList.vue
- Upgraded dependencies to include patch for nested dependency of "node-ipc". The patch pins the version, so it will still be included in "package-lock.json".
- Updated OpenShift NodeJS version in build pipeline.
- Fixed some linting errors in "Child.vue" and "ReviewTableList.vue".
=> JHA: "node-ipc" fix.

jha/package-lock.json, jha/src/services/api-service.js
=> Fix FPC-only address payload

jha/package-lock.json, jha/package.json
=> JHA: version bump (v0.1.38).

jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> Clear unused fields in ah, spouse, child

jha/src/constants/radio-options.js
=> Switch gender x label back

jha/src/components/enrolment/ReviewTableList.vue
Changes Temporary Resident status to display "Moved from province/jurisdiction" instead of previous "Moved from location"
=> Update moved from label (JHA-93)

jha/src/components/enrolment/ReviewTableList.vue
=> Add dynamic NOA year on review page

jha/src/services/api-service.js, jha/src/views/enrolment/SuppBenInfoPage.vue
=> Fix supben payload issues

jha/package-lock.json, jha/package.json
=> Bump version

jha/src/components/enrolment/ReviewTableList.vue, jha/src/services/api-service.js, jha/src/views/enrolment/ContactInfoPage.vue
Bug fix
Now only mailing address fields are shown for non-MSP applications and the corresponding change has been made in the review page and payload
The branch is poorly named, my apologies
=> Mailing adress only for non-MSP apps

jha/src/views/enrolment/ConsentPage.vue
content update
Update FPC declaration and consent to match wireframe
=> fpc consent page text updates

jha/src/services/api-service.js, jha/tests/unit/services/apiService.spec.js
chore
Program area change for FPC PoA docs requested from kevin. Refactored the api-service tests a bit to not mutate `dummyData` and formatted the file
=> set program area to PHARMANET for fpc PoA docs

jha/src/services/api-service.js, jha/tests/unit/services/apiService.spec.js
Bug fix
Supp Ben documents addition was outside of `if` statement, causing an error if not including SB. Moved logic to if statement and added a regression test for it
=> move sb documents into if statement, regression test

jha/package-lock.json, jha/package.json
=> bump npm package version

msp/src/app/modules/enrolment/pages/child-info/child-info.component.html
Content update
The `msp-canadian-status` component made this a little wonky but I worked around it
=> Add tipbox to add child section in enrolment

jha/src/services/api-service.js
Bug fix: old default poa value incompatible with new middleware logic
=> remove default poa value from suppben

jha/src/views/enrolment/MSPEligibilityPage.vue
=> Wording update on eligibility journey

jha/src/views/enrolment/PersonalInfoPage.vue
content update
The error text from early March on the ticket seems to be resolved already, messages match for spouse and account holder already.
=> update text content for account holder info

jha/src/components/enrolment/Child.vue
Feature addition
What it looks like:
=> Add tipbox

jha/src/views/enrolment/DocumentsPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue, jha/tests/e2e/fixtures/fpcStandaloneRequest.js, jha/tests/e2e/fixtures/fullApplication.js, jha/tests/e2e/fixtures/sbStandaloneRequest.js, jha/tests/e2e/helpers.js, jha/tests/e2e/specs/FPC.js, jha/tests/e2e/specs/SB.js, jha/tests/e2e/specs/fullApplication.js, jha/tests/e2e/support/commands.js, jha/tests/e2e/support/index.js
chore
Adds integration tests for suppBen standalone, FPC standalone, and applying for all 3. Only changes to application code are adding IDs for selectors
=> Integration tests

jha/package-lock.json, jha/package.json
=> bump package version

jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> text updates

jha/src/components/enrolment/Child.vue, jha/src/constants/select-options.js, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue
Content update
Children dependents cannot be married so we removed the marriage cert from the available dropdown options (Ernesto approved)
=> Update wordings and select box

jha/package-lock.json, jha/package.json
chore
bumping version to deploy to test
=> bump npm version

jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue
=> Adjust elgiibility error message styles

jha/package-lock.json, jha/package.json
=> Bump JHA version to 0.1.50

jha/src/App.vue, jha/src/components/ConsentModal.vue, jha/src/components/EligibilityQuestionnaireHeader.vue, jha/src/components/IdTable.vue, jha/src/components/SampleImageTipBox.vue, jha/src/components/enrolment/Child.vue, jha/src/constants/immigration-status-types.js, jha/src/router/routes.js, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/ConsentPage.vue, jha/src/views/enrolment/DocumentsPage.vue, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FPCareInfoPage.vue, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
A lot of files changed, but just text. The only net new components are:
- A table of ID options to replace the old `ul` of options
- Made the eligibility header a shared component to help keep the text in sync
=> Wireframe matching

jha/src/components/enrolment/Child.vue, jha/src/constants/html-validations.js, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
chore
Updating firstname and middlename maxlength requirements. Refactored to use a variable since this will likely change again and be shared across all the user info pages
=> update maxlength for names, use constants to revert/change easily

jha/src/constants/html-validations.js
=> change middlename to 30 characters maxlength

jha/src/components/enrolment/ReviewTableList.vue
Bug fix
Logic to add phone number to  the review table was nested inside `if (!this.$store.state.enrolmentModule.isMailSame || !this.isApplyingForMSP) {`. Moved it outside the `if` block to display it at the end of the contact info section for any application type
=> always show phone number if included

jha/package-lock.json, jha/package.json, jha/tests/e2e/fixtures/fpcStandaloneRequest.js, jha/tests/e2e/fixtures/fullApplication.js, jha/tests/e2e/fixtures/mspStandaloneRequest.js, jha/tests/e2e/fixtures/sbStandaloneRequest.js, jha/tests/e2e/specs/FPC.js, jha/tests/e2e/specs/MSP.js, jha/tests/e2e/specs/SB.js, jha/tests/e2e/specs/fullApplication.js, jha/tests/e2e/support/commands.js
chore
- Bumps common-lib version and ran npm patch to prepare for test deploy
- Other changes are for e2e tests, to use the common-lib-vue date formatter in fixtures and test the phone number shows up in all cases (review page and payload)
=> E2e phone test

jha/package-lock.json, jha/src/components/IdTable.vue, jha/src/router/index.js, jha/src/router/routes.js, jha/src/views/MaintenancePage.vue, jha/src/views/PageNotFoundPage.vue, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/ConsentPage.vue, jha/src/views/enrolment/ContactInfoPage.vue, jha/src/views/enrolment/DocumentsPage.vue, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FPCareInfoPage.vue, jha/src/views/enrolment/FormSelectionPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/ReviewPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SubmissionErrorPage.vue, jha/src/views/enrolment/SubmissionPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> Add landmarks, fix table, add dynamic page titles

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/ContactInfoPage.vue, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FPCareInfoPage.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> Use new vers of common lib, add required props

jha/package-lock.json, jha/package.json
=> Version bump 0.1.54

jha/package-lock.json, jha/package.json
=> Version bump: 0.1.55

jha/package-lock.json, jha/package.json, jha/src/App.vue
Bug fix, version bump 
For some reason, the `.children.length` was always > 0, even when it had no visible children. But `Wormhole.hasContentFor` works by itself so it doesn't matter
=> Fix aria-hidden attribute, bump version

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue
chore
Remove errant debugger statement, update common-lib version
=> remove errant debugger, bump common-lib version

jha/package-lock.json, jha/package.json
Chore (bump common lib version and app version)
=> Bump version of common lib, bump app version

jha/package-lock.json, jha/package.json
=> Bump version 0.1.58

jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/MSPEligibilityPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
Feature addition / bug fix (check PHN is from BC via first digit)
=> Add first digit error check for previous phns and msp elig blurb

msp/package-lock.json, msp/package.json, msp/src/app/modules/account/components/person-card/person-card.component.spec.ts
Feature addition, digitial signatures now work with updated moh-common-lib
Had to fix test for country label to "jurisdiction"
=> Use new common-lib, update deps

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
Content update
Since this is likely the last change to JHA before release, I bumped to the first major version
=> JHA wording updates

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> CUAET blurb on child page

jha/package-lock.json, jha/package.json, jha/src/components/IdTable.vue, jha/src/constants/document-types.js
Content update
Changes specifically requested by Anthony Forrest
=> Last minute JHA changes

jha/src/views/enrolment/ContactInfoPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> Add negative number error handling and PO box label

jha/package-lock.json, jha/package.json, jha/src/views/enrolment/ContactInfoPage.vue
Content update, chore (version bump)
=> Residential address correction

msp/package-lock.json, msp/package.json, msp/src/app/app-routing.module.ts, msp/src/app/app.component.ts, msp/src/app/pages/landing/landing.component.html, msp/src/app/pages/landing/landing.component.ts
=> Remove old enrolment + suppben, add redirect

msp/package-lock.json, msp/package.json
Chore/bug fix (bump version, update common lib to add click functionality to fileuploader icon)
=> Use new version of ng common lib, 3.6.2

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue
Bug fix
Hard to find, easy to fix
=> Fix JHA child bug

jha/package-lock.json, jha/package.json, jha/src/App.vue, jha/src/services/api-service.js, jha/src/views/enrolment/ConsentPage.vue
Bug fix and feature addition (more logging)
=> Add details to logging and trim field length if over max

jha/src/services/api-service.js, jha/src/views/enrolment/ContactInfoPage.vue
Bug fix
Remember you'll have to bump the version before deploying (leaving that for now in case you end fixing more bugs before the next release)
=> Fix address bug and trim field lengths before submission

jha/src/App.vue, jha/src/store/modules/app-module.js, jha/src/views/MaintenancePage.vue
=> Add custom message settable from spa-env-server

jha/src/views/enrolment/ConsentPage.vue
Content update
GitHub isn't allowing image uploads right now (s3 error in the console) so I will message you what the change looks like
=> Add notice for pre-submit to JHA

jha/src/views/enrolment/ConsentPage.vue
Content update kind of (changing what is logged slightly)
=> Only log the message rather than unrelated info

jha/src/components/enrolment/Child.vue
Bug fix
Replacing special characters before truncating prevents fields from being accidentally over length. (a single ½ becomes 1 / 2 for example)
Doing this replacement here ensures the users sees the final result before it is submitted. There is also a truncation in the api-service.js just in case but if we rely only on that we might receive partially complete address lines.
=> Add address fix to child component to prevent overlength submissions

jha/src/views/enrolment/ConsentPage.vue
Bug fix
This is just a failsafe to prevent duplicate submissions without users leaving the page. There is still the possibility of users navigating away before the submission is complete and submitting again causing a duplicate. Hopefully the notice we added last week will reduce the number of times that happens.
=> Exit submit function if already loading

jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SubmissionPage.vue
Content update, feature addition
As per requested by Ernesto + comms
=> Add content to submission page and jurisdiction labels on ah, sp, ch

jha/package-lock.json, jha/package.json
=> Bump version to 1.0.9

jha/src/services/api-service.js, jha/src/views/enrolment/SubmissionPage.vue, jha/tests/unit/views/enrolment/SubmissionPage.spec.js
=> JHA changes

jha/README.md, msp/README.md
=> Readme update

jha/package-lock.json, jha/src/services/api-service.js, jha/tests/e2e/fixtures/fullApplication.js, jha/tests/e2e/fixtures/mspStandaloneRequest.js, jha/tests/e2e/fixtures/sbStandaloneRequest.js, jha/tests/e2e/specs/FPC.js, jha/tests/e2e/specs/MSP.js, jha/tests/e2e/specs/SB.js, jha/tests/e2e/specs/fullApplication.js, jha/tests/e2e/support/commands.js
- [] Unit tests for these changes were added (if applicable)
--Adds substring and replace special characters function to the mailing address city field to prevent middleware errors
Unit + E2E tests pass. Npm lint passes. Ran npm audit fix.
=> Mailing address length fix (JHA)

jha/package-lock.json, jha/package.json, msp/package-lock.json, msp/package.json
Version bump to cover microservice updates
=> Version bump (JHA 1.0.10 -> 1.0.11, MSP 3.5.1 -> 3.5.2)

msp-service/package-lock.json, msp-service/package.json
Reverts the JWT version so the pods will build in OpenShift (they fail on JWT 9.0.0 or later)
=> Revert jwt version

msp/src/app/modules/account/pages/child-info/child-info.component.html, msp/src/app/modules/account/pages/home/home.component.html
=> Update texts for home page and child page in MSP DEAM

msp/src/app/modules/account/pages/home/home.component.html, msp/src/app/modules/account/pages/home/home.component.scss
=> fixed: removed alert and centered text in home page

msp/src/app/modules/account/pages/sending/sending.component.ts
=> fix: update the logs to remove any PI data logging

msp/package-lock.json, msp/package.json
=> fix: version bump to 3.5.4

msp-service/src/index.js, splunk-forwarder/src/splunklogger.js
Code changes to facilitate Splunk migration
`npm run build` works for both applications. `npm run start` was NOT tested due to requiring passed down variables that I don't have time to dig for at the moment
=> Splunk to dynatrace migration (splunk forwarder, msp service)

address-service/package-lock.json, address-service/package.json
=> Address service vulnerability fixes

msp-service/package-lock.json, msp-service/package.json, splunk-forwarder/package-lock.json, splunk-forwarder/package.json
`npm run test:unit` run for JHA. `npm run test:e2e` run for JHA. `npm run test` run for MSP. `npm run build` run for msp-service and splunk-forwarder.
`npm audit` vulnerabilities were NOT updated, as these are out of scope.
=> Dynatrace version bump (msp service 1.0.0 -> 2.0.0, splunk forwarder 0.9.0 -> 1.0.0)

address-service/package-lock.json, address-service/package.json
=> fix: revert back dependencies for address-service

msp/src/app/modules/account/pages/confirmation/confirmation.component.html
=> fix: text changes in confirmation page

jha/package-lock.json, jha/package.json
Version bump to cover the Vue 3/Vite upgrade
Verified that the version number in the lower right corner still displays correctly
=> Version bump (JHA 1.0.11 -> 2.0.0)

jha/package-lock.json, jha/package.json, jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue
=> DE-810: Update minor text change in Working Permit Holder

jha/package-lock.json, jha/package.json, jha/src/components/ConsentModal.vue, jha/src/components/IdTable.vue, jha/src/components/SuppBenWidget.vue, jha/src/components/enrolment/Child.vue, jha/src/components/enrolment/FPCWidget.vue, jha/src/helpers/fpc-helpers.js, jha/src/views/enrolment/ChildInfoPage.vue, jha/src/views/enrolment/ContactInfoPage.vue, jha/src/views/enrolment/FPCareEligibilityPage.vue, jha/src/views/enrolment/FPCareInfoPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SpouseInfoPage.vue, jha/src/views/enrolment/SuppBenEligibilityPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue, jha/tests/unit/helpers/fpc-helpers.spec.js
=> JHA bug fixes

jha/src/views/enrolment/FPCareInfoPage.vue, jha/src/views/enrolment/PersonalInfoPage.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> fix: add bug fixes version 2

jha/src/components/enrolment/Child.vue, jha/src/views/enrolment/SuppBenInfoPage.vue
=> fix: update wording changes and styling
